Bruk av AzureAD for veilarboppfolging
navikt/veilarbdirigent pull request #123
Opened 2022-12-13 11:51 UTC by dragutin-nav

2022-12-14 09:59 UTC, dragutin-nav commented on nais-q.yaml
> +        extra:
```suggestion

```

2022-12-14 09:59 UTC, dragutin-nav commented on nais-q.yaml
> +          - NAVident
```suggestion

```

2022-12-14 10:00 UTC, dragutin-nav commented on nais.yaml
> +          - azp_name
We don't need this extra claims

```suggestion
   
```

2022-12-14 12:14 UTC, dragutin-nav commented on src/main/java/no/nav/veilarbdirigent/config/FilterConfig.java
> +
Its not necessary to have this bean
```suggestion
 
```

2022-12-14 12:14 UTC, dragutin-nav commented on nais-q.yaml
> +
```suggestion
```

2022-12-14 12:15 UTC, dragutin-nav commented on nais.yaml
> +
```suggestion
```

2022-12-15 08:14 UTC, hakonph requested changes

2022-12-15 08:14 UTC, hakonph commented on src/main/java/no/nav/veilarbdirigent/config/ClientConfig.java
> +        String tokenScope = String.format(
burde denne trekkes ut i en egen bønne?

2022-12-15 08:14 UTC, hakonph commented on src/main/java/no/nav/veilarbdirigent/service/OppfolgingStartetConsumerService.java
> +        log.info("Oppfolging startet melding 1");
disse må rydes opp i

2022-12-15 15:08 UTC, slovrid commented on src/main/java/no/nav/veilarbdirigent/client/veilarboppfolging/VeilarboppfolgingClientImpl.java
> +        log.info("Hent oppfolgingsperioder");
Denne var vel kun for debugging reasons ...

```suggestion
```

2022-12-15 15:08 UTC, slovrid commented on src/main/java/no/nav/veilarbdirigent/client/veilarboppfolging/VeilarboppfolgingClientImpl.java
> +        }
Denne var vel kun for debugging reasons ...
```suggestion
```

2022-12-15 20:15 UTC, dragutin-nav commented on src/main/java/no/nav/veilarbdirigent/config/ClientConfig.java
> +        String tokenScope = String.format(
Jeg flyttet scope verdi til env variable

2022-12-16 08:35 UTC, hakonph approved these changes

2022-12-16 09:15 UTC, closed without merging